/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#afecfd",
        "secondary-fixed-dim": "#ffb690",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fd761a",
        "tertiary-fixed": "#cce5ff",
        "on-primary-fixed": "#001f26",
        "inverse-surface": "#283044",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#ffdbca",
        "tertiary-container": "#00527e",
        "on-background": "#131b2e",
        "on-secondary-container": "#5c2400",
        "on-surface-variant": "#40484b",
        "outline-variant": "#bfc8cb",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "surface-container": "#eaedff",
        "surface": "#faf8ff",
        "on-primary-fixed-variant": "#004e5c",
        "surface-container-highest": "#dae2fd",
        "surface-tint": "#266675",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001d31",
        "primary-fixed-dim": "#93d0e0",
        "on-primary-container": "#8cc8d8",
        "secondary": "#9d4300",
        "tertiary": "#003a5b",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed-variant": "#004b73",
        "primary-container": "#0b5563",
        "tertiary-fixed-dim": "#93ccff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#341100",
        "on-primary": "#ffffff",
        "outline": "#70787b",
        "on-secondary-fixed-variant": "#783200",
        "background": "#faf8ff",
        "inverse-primary": "#93d0e0",
        "on-tertiary-container": "#81c5ff",
        "primary": "#003d48",
        "on-surface": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "teal": {
          700: "#0B5563",
          800: "#08404a",
          900: "#052b32",
        },
        "accent": "#F97316"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-2": "0.125rem",
        "space-4": "0.25rem",
        "space-8": "0.5rem",
        "space-12": "0.75rem",
        "space-16": "1rem",
        "space-20": "1.25rem",
        "space-24": "1.5rem",
        "space-32": "2rem",
        "space-40": "2.5rem",
        "space-48": "3rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        sans: ["Inter", "Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Inter"],
        "display-lg": ["Manrope"],
        "body-lg-medium": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Manrope"],
        "label-caps": ["Inter"],
        "headline-xl": ["Manrope"],
        "body-sm": ["Inter"],
        "data-mono-lg": ["JetBrains Mono"],
        "body-md-medium": ["Inter"],
        "data-mono-md": ["JetBrains Mono"],
        "headline-md": ["Manrope"]
      },
      fontSize: {
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg-medium": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "data-mono-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md-medium": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "data-mono-md": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
